### ISSUE TITLE
submenu bug when height of menus increased.

### ISSUE THREAD

**Issue by blazespinnaker** [iVis-at-Bilkent/cytoscape.js-context-menus#53] opened 2020-09-25 20:12 UTC
There is a bug when you increase the height of the top level menus in the css.  The submenus are not adjacent (they are to the right and above) so you can't mouse over from the top menu to the submenus without them closing first.  I can attempt a PR if someone provides a brief overview of the rendering flow of submenus.

**Comment by ugurdogrusoz** [comment] 2020-09-27 08:12
@blazespinnaker Thanks for reporting this problem. Can you please provide your code to reproduce this code? At least a screenshot of what you see.

**Comment by msalihaltun** [comment] 2020-10-07 12:05
I couldn't reproduce this. Can be adressed if more information is provided in the future.

**Comment by ugurdogrusoz** [comment] 2020-10-07 12:06
Closing now since there hasn't been a response.

**Closed by ugurdogrusoz** 2020-10-07 12:06 UTC
